services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app:z
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_URL: http://0.0.0.0:3000
    command: npm start
    stdin_open: true
    tty: true
